# Welcome to  Shop Configuration
# Thank you for using the plugin.
# Author: Prathamesh
# Version: 0.1.3
# Dependency: Vault

# Name of the Main GUI (Color Codes are accepted)
shopMenuName: "Server Shop"

# Size of the Main GUI (Available sizes: 9, 18, 27, 32, 45, 54)
shopMenuSize: 54

#Item to fill empty slots with (Use correct Item Material)
shopMenuFiller: BLACK_STAINED_GLASS_PANE

#Close Menu Button options
closeButton:
  material: BARRIER
  slot: 49
  name: "&cClose"

#Items for the Main Menu
#
# material: material used in main menu
# shop: name of the shop to open (available shops: builder, farmer, decorator, miner, fisherman, misc)
# name: display name of the item
# slot: slot of the item in main menu
# lore: lore of the item in main menu
#

mainMenuItems:
  1:
    material: GRASS_BLOCK
    shop: builder
    name: "&eBuilder"
    slot: 10
    lore:
      - "&8Building"
      - ""
      - "&7Browse the items The Builder has"
      - "&7brought for you to trade!"
      - ""
      - "&aClick to view!"
  2:
    material: WHEAT
    shop: farmer
    name: "&eFarmer"
    slot: 12
    lore:
      - "&8Farming"
      - ""
      - "&7Browse the items The Farmer has"
      - "&7brought for you to trade!"
      - ""
      - "&aClick to view!"
  3:
    material: SUNFLOWER
    shop: decorator
    name: "&eDecorator"
    slot: 14
    lore:
      - "&8Decoration"
      - ""
      - "&7Browse the items The Decorator has"
      - "&7brought for you to trade!"
      - ""
      - "&aClick to view!"
  4:
    material: IRON_INGOT
    shop: miner
    name: "&eMine Merchant"
    slot: 16
    lore:
      - "&8Mining"
      - ""
      - "&7Browse the items The Miner has"
      - "&7brought for you to trade!"
      - ""
      - "&aClick to view!"
  5:
    material: SALMON
    shop: fisherman
    name: "&eFish Merchant"
    slot: 19
    lore:
      - "&8Fishing"
      - ""
      - "&7Browse the items The Fisherman has"
      - "&7brought for you to trade!"
      - ""
      - "&aClick to view!"
  6:
    material: BEACON
    shop: misc
    name: "&eAdventurer"
    slot: 21
    lore:
      - "&8Misc"
      - ""
      - "&7Browse the items The Adventurer has"
      - "&7brought for you to trade!"
      - ""
      - "&aClick to view!"